### ISSUE TITLE
Unable to use in React Native

### ISSUE THREAD

**Issue by jjalan** [logdna/logdna-browser#21]
I installed the package via:

```
yarn add @logdna/browser
```

However, metro complains at runtime while using it

```
error: Error: While trying to resolve module `@logdna/browser` from file `/Users/user/Developer/app/index.js`, the package `/Users/user/Developer/app/node_modules/@logdna/browser/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/user/Developer/app/node_modules/@logdna/browser/index`. Indeed, none of these files exist:
```

**Comment by TerryMooreII** [comment]
@jjalan Currently the browser logger does not support React Native.  React Native is something that we are hoping to support in the future but we currently don't have a timeline as to when this will get released.  I will let the others on the team know that there is an increased interest in using the browser logger with React Native so they can adjust the timelines as needed.
