### ISSUE TITLE
What version of the library is actually the latest?

### ISSUE THREAD

**Issue by boonya** [logdna/logdna-browser#61]
Hello there.
I noticed that [the package deployed to the npm repo has version 1.4.1](https://www.npmjs.com/package/@logdna/browser) meanwhile here at the github repository [it is 2.0.10](https://github.com/logdna/logdna-browser/releases/tag/v2.0.10).
So, my question is this package maintaned or abandoned? How can I install 2.0.10 if there is no such package anywhere?

**Comment by TerryMooreII** [comment]
@boonya The latest is the 2.0.10 version, we released 2.x to npm with the `beta` tag a while back in order to do some testing.  This beta tag needs to be removed and released to latest, asap.  In the mean time you can install it with `npm install @logdna/browser@beta`.

**Comment by boonya** [comment]
Thank you for the quick answer
